version: '3.7'

services:
  web:
    build: ./
    container_name: ItFox_TPB_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db


  db:
    image: postgres:12
    container_name: ItFox_TPB_db
    volumes:
      - ItFox_TPB_postgers_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: ItFox_TPB_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
    depends_on:
      - web

volumes:
  ItFox_TPB_postgers_data:

